twitter_anidata_consumer_key = "mCllXqP17zEIZUx4pv2uLwo8b"
twitter_anidata_consumer_secret = "uk6nLkwpDmInvrzTazNLtr7JIAIz6tOCsSEOTQRD6bpc46vTPM"
twitter_anidata_access_token = "347358365-U4i2mdcdrUtU6S28pgNUmW3fJgogQKDBBYOcIkY8"
twitter_anidata_access_token_secret = "	yAFgtqGFyUfpJZpZrgRGd9BUA3QOJFcR7xlcFujpHtNGS"